### PR TITLE
Add 14.0 beta(From Xcode_12_beta.xip)

### PR DESCRIPTION
**Pull request by moonclock**
update DeviceSupport, Add 14.0 beta(From Xcode_12_beta.xip)

### CODE REVIEW

**Comment by mycroftcanner** [comment]
have you tested it?

**Comment by moonclock** [comment]
> have you tested it?

Yes, I used it all afternoon (Xcode 11.5 & iPhoneOS 14.0 Beta).

**Comment by LunightLab** [comment]
:) good

**Comment by karlolopez** [comment]
Anybody knows how to use this with Xcode 10.3?

**Comment by istornz** [comment]
Works perfectly thanks !

**Comment by moonclock** [comment]
> Anybody knows how to use this with Xcode 10.3?

I didn't test the deviceSupport on Xcode 10.3, This version is too old, but the following method is always effective

Unzip 14.0 beta (From Xcode_12_beta.xip).zip
To /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport

**Comment by moonclock** [comment]
@iGhibli Please marge this request.

**Comment by lutang123** [comment]
Hi, I am new in App development, can anyone share how exactly I should add 14.0(From Xcode_12_beta.xip)? I can't see any file to download, and where I should add? Thank you!

**Comment by moonclock** [comment]
> Hi, I am new in App development, can anyone share how exactly I should add 14.0(From Xcode_12_beta.xip)? I can't see any file to download, and where I should add? Thank you!

This is a pull request, so you can't download file from this page, you can try click on this [link](https://github.com/iGhibli/iOS-DeviceSupport/tree/master/DeviceSupport) to download what you want.

After downloading, use it like this
Unzip 14.0 beta (From Xcode_12_beta.xip).zip
To /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport

**Comment by dovanvu1792** [comment]
Can run emulator with Xcode 11.1 and emulator 14.0 beta?

**Comment by moonclock** [comment]
> Can run emulator with Xcode 11.1 and emulator 14.0 beta?

It is feasible in theory, but it is recommended to try the latest DeviceSupport on the master, this pull request is an old version

**Comment by thinhlifetechvn** [comment]
> > Hi, I am new in App development, can anyone share how exactly I should add 14.0(From Xcode_12_beta.xip)? I can't see any file to download, and where I should add? Thank you!
> 
> This is a pull request, so you can't download file from this page. pleases click on this [link](https://github.com/iGhibli/iOS-DeviceSupport/tree/master/DeviceSupport) to download what you want.
> 
> After downloading, use it like this way:
> Unzip 14.0 beta (From Xcode_12_beta.xip).zip
> To /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport

I did as instructed, but still got the error @moonclock 
Error launching app. Try launching from within Xcode via:
    open ios/Runner.xcworkspace

Your Xcode version may be too old for your iOS version.
═══════════════════════════════════════════════════════════════════════════════════
2020-10-22 11:57:30.404 ios-deploy[68339:383738] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
Could not run build/ios/iphoneos/Runner.app on d9eaec8d23e691b9fbce0fe2b4cc799c2f448593.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone.

**Comment by moonclock** [comment]
> > > Hi, I am new in App development, can anyone share how exactly I should add 14.0(From Xcode_12_beta.xip)? I can't see any file to download, and where I should add? Thank you!
> > 
> > 
> > This is a pull request, so you can't download file from this page. pleases click on this [link](https://github.com/iGhibli/iOS-DeviceSupport/tree/master/DeviceSupport) to download what you want.
> > After downloading, use it like this way:
> > Unzip 14.0 beta (From Xcode_12_beta.xip).zip
> > To /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport
> 
> I did as instructed, but still got the error @moonclock
> Error launching app. Try launching from within Xcode via:
> open ios/Runner.xcworkspace
> 
> Your Xcode version may be too old for your iOS version.
> ═══════════════════════════════════════════════════════════════════════════════════
> 2020-10-22 11:57:30.404 ios-deploy[68339:383738] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
> Could not run build/ios/iphoneos/Runner.app on d9eaec8d23e691b9fbce0fe2b4cc799c2f448593.
> Try launching Xcode and selecting "Product > Run" to fix the problem:
> open ios/Runner.xcworkspace
> 
> Error launching application on iPhone.

I did not encounter this problem, but you try solve it by restarting the computer

**Pull request merged**
