### PR TITLE
Add iOS 16.0_beta3 (From Xcode_4_beta_3.xip) Support files 

### PR DESCRIPTION
**Pull request by AnasAlmomany**

### CODE REVIEW

**Comment by AnasAlmomany** [comment]
Fresh from the oven! Please review and merge

**Comment by AnasAlmomany** [comment]
@iGhibli  Please check

**Comment by ejbills** [comment]
mind adding beta 6?

**Review by kuyazee — APPROVED** [review]
Works on my end :D @iGhibli for you to merge

**Comment by kot-ezhva** [comment]
can u add 16.1 pls?

**Pull request merged**
